### ISSUE TITLE
error TS2322: Type 'DynamicModule' is not assignable to type 'Type<any> | DynamicModule | Promise<DynamicModule> | ForwardReference<any>'

### ISSUE THREAD

**Issue by mohammadfarooqi** [anchan828/nest-sendgrid#1]
Hi

I am getting the following error when trying to import this module:

 error TS2322: Type 'DynamicModule' is not assignable to type 'Type<any> | DynamicModule | Promise<DynamicModule> | ForwardReference<any>'.
  Type 'DynamicModule' is not assignable to type 'ForwardReference<any>'.
    Property 'forwardRef' is missing in type 'DynamicModule'.

Can you advise why this is happening?

Thanks.

**Comment by anchan828** [comment]
Hi, sorry for late reply. 
Did you install @nestjs/(common and core) packages?

If you have issue, please re-open or comment. thanks.
