### ISSUE TITLE
Testing with sendgridservice

### ISSUE THREAD

**Issue by ayepRahman** [anchan828/nest-sendgrid#380]
Hi, can you show some example on how can mock `.send` in my unit testing using jest?

**Comment by anchan828** [comment]
Hi,

https://github.com/anchan828/nest-sendgrid/blob/master/packages/sendgrid/src/sendgrid.service.spec.ts#L67-L70

or

```typescript
const service = app.get<SendGridService>(SendGridService);
jest.spyOn(sendgrid, "send").mockResolvedValue([{} as any, {}]);
```

or

```typescript
const mockSend = jest.fn();
jest.spyOn(sendgrid, "send").mockImplementationOnce(mockSend);
```

**Comment by ayepRahman** [comment]
@anchan828 thanks for the quick response! Awesome package!
